# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ba2eabecc203dd12465af2fe88702fe1b4758de53e3d140533d0a703578ff7fbee8152a0c8aa1ce0125318041f6ec5b3b7dfe9817c5ca730f6744b6bf54d016

test:
  secret_key_base: 3ab679265f04ba410eaa7433919cdb2c334dffbe16576665730af857fa98dc6752d6e0e7b36687b29fadac144423b9d2c19e04b2235bf882e969ee54175a3ef0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
